Squid:
  image: sameersbn/squid:3.3.8-23
  ports:
    - "3128:3128"
  volumes:
    - /tmp/cache:/var/spool/squid3
    - ./squid.conf:/etc/squid3/squid.conf
    - ./config/passwords:/etc/squid3/passwords
  restart: always

